// tuning-export.js
// Pure helpers for generating SCL / KBM / TUN text

export function generateSclFileContent(scaleName, scaleDegrees) {
  let sorted = [...scaleDegrees].sort((a, b) => a.floatVal - b.floatVal);
  let relevant = sorted.filter(d => d.floatVal < 2.000001);
  let numIntervals = relevant.length - 1;
  if (numIntervals < 1) numIntervals = 1;
  let lines = [];
  lines.push(`! ${scaleName}`);
  lines.push(`${scaleName}`);
  lines.push(`${numIntervals}`);
  lines.push("!");
  for (let i = 1; i < relevant.length; i++) {
    let ratio = relevant[i].floatVal;
    let cents = 1200 * Math.log2(ratio);
    lines.push(cents.toFixed(5));
  }
  return lines.join("\n") + "\n";
}

export function generateKbmFileContent(
  comment,
  scaleDegrees,
  refMidi,
  refFreq,
  lowestMidi,
  highestMidi
) {
  let lines = [];
  lines.push(`! ${comment}`);
  lines.push("!");
  const mapSize = (highestMidi - lowestMidi) + 1;
  lines.push(`${mapSize}`);
  lines.push(`${lowestMidi}`);
  lines.push(`${highestMidi}`);
  lines.push(`${refMidi}`);
  lines.push("0");
  lines.push(`! Reference frequency for MIDI note ${refMidi} = ${refFreq.toFixed(3)} Hz`);
  let sorted = [...scaleDegrees].sort((a, b) => a.floatVal - b.floatVal);
  const scaleCount = sorted.length;
  for (let k = lowestMidi; k <= highestMidi; k++) {
    let cycleLen = scaleCount - 1;
    if (cycleLen < 1) cycleLen = 1;
    let indexInScale = (k - lowestMidi) % cycleLen;
    lines.push(`${indexInScale}`);
  }
  return lines.join("\n") + "\n";
}

export function generateTunFileContent(scaleDegrees, refMidi, refFreq) {
  let sorted = [...scaleDegrees].sort((a, b) => a.floatVal - b.floatVal);
  let lines = [];
  lines.push("! Generated by Scale WKSP");
  lines.push("table begin");
  for (let i = 0; i < sorted.length; i++) {
    let ratio = sorted[i].floatVal;
    let cents = 1200 * Math.log2(ratio);
    lines.push(` ${i + 1}) ${cents.toFixed(5)}`);
  }
  lines.push("table end");
  lines.push("octave 1200.0");
  lines.push(`middle note ${refMidi}`);
  lines.push(`base freq ${refFreq.toFixed(5)}`);
  return lines.join("\n") + "\n";
}
